apiVersion: apps/v1
kind: Deployment
metadata:
  name: skippy-network
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skippy-network
  template:
    metadata:
      labels:
        app: skippy-network
    spec:
      nodeSelector:
      containers:
      - name: skippy-network
        image: keniack/skippy-network:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        env:
        - name: redis_host
          value: 10.244.0.9
---
apiVersion: v1
kind: Service
metadata:
  name: skippy-network
  namespace: default
  labels:
    app: skippy-network
spec:
  type: NodePort
  selector:
    role: master
    app: skippy-network
  ports:
  - port: 5002
    targetPort: 5002
    nodePort: 31501
