apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telemd
  labels:
    tier: node
    app: telemd
spec:
  selector:
    matchLabels:
      name: skippy-telemd
  template:
    metadata:
      labels:
        name: skippy-telemd
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: telemd
        image: keniack/telemd:0.2
        imagePullPolicy: Always
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_ADMIN"]
        env:
        - name: telemd_redis_host
          value: 10.244.0.73
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: netdevattributes
          mountPath: /sys/class/net
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: netdevattributes
        hostPath:
          path: /sys/class/net
