apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemd
  template:
    metadata:
      labels:
        app: telemd
    spec:
      containers:
      - name: telemd
        image: edgerun/telemd:latest
        env:
        - name: telemd_redis_host
          value: 10.109.167.109
---
apiVersion: v1
kind: Service
metadata:
  name: telemd-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    telemd: monitor
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30001
